# Generated by Django 4.2 on 2023-12-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_reservations_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
