# Generated by Django 4.2 on 2024-01-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
